spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/notas
    username: notas
    password: notas
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
